### ISSUE TITLE
Discriminator Pre-trained Weight and Training Script

### ISSUE THREAD

**Issue by humayun** [ivclab/BigGAN-Generator-Pretrained-Pytorch#2]
Hi,

Any plan to shared pre-trained discriminator weights and training script?

best,

**Comment by Jia-HongHenryLee** [comment]
@andrewhsiehth have question~~

**Comment by humayun** [comment]
I am looking to retrain your GAN model on my dataset as I have very small dataset and problem is that I need to generate high resolution images like 512 or 1024 pixels. Are discriminative model is publically available and training script?

**Comment by ifndef012** [comment]
This project only converted the pre-trained generator model provided by tensorflow-hub. Unfortunately, since they did not provide their discriminator model, I could not convert it. If you want to train the complete GAN model, the author had released his Pytorch scripts which may be helpful to you. Thanks.
